### PR TITLE
Adding Code Examples for <form> and Response.Htmx() in Htmx.Net

### PR DESCRIPTION
**Pull request by bingzer**
Hi @khalidabuhakmeh,

I'm adding a few helpful code examples for using <form> elements and the Response.Htmx() function. These examples make it easier for users to understand and use these features.

Hopefully, we can slowly build the Htmx.Sample project to showcase the simple integration of Htmx and Asp.Net in the future.

Please check it out and let me know what you think.

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
The samples look good. I'll have to download your branch to see what the heck VS did to the solution and project files. (It's probably ok). Cheers 👍

**Comment by bingzer** [comment]
Awesome! Sounds good.

**Comment by khalidabuhakmeh** [comment]
Thanks for the samples. If you haven't seen it already, I've created this series to help folks.

https://www.jetbrains.com/dotnet/guide/tutorials/htmx-aspnetcore/

**Comment by bingzer** [comment]
> Thanks for the samples. If you haven't seen it already, I've created this series to help folks.
> 
> https://www.jetbrains.com/dotnet/guide/tutorials/htmx-aspnetcore/

I'm not a aware of this. Thanks!.

Is there a plan to merge the samples you did to this project's sample library?

**Comment by khalidabuhakmeh** [comment]
@bingzer not at this time. I really created the sample project because I found it the best way to test things.

That said, maybe I should look into using Playwright to automate some of the tests, but at that point I'm still building a sample app. 😅

**Pull request merged**
