### PR TITLE
Support updating the antiforgery token when a boost occurs

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
It can be problematic if a token has been used previously.

Note: This updates to HTMX 1.9.2 (the latest as of this commit). #15

### CODE REVIEW

**Comment by juchom** [comment]
I've made some quick tests, and it works well.

Thanks for this quick fix.

**Comment by AlexZeitler** [comment]
@khalidabuhakmeh Sorry, I won't be able to review it before Friday in a way to give reasonable feedback.

**Comment by khalidabuhakmeh** [comment]
👋 Hey folks, I've added a new endpoint for the anti-forgery script, which allows for referencing the script in a `<script src="" defer></script>` tag. This is the better option using modern approaches for JavaScript.

I still left the old approach but left a message about the newer approach.

**Comment by AlexZeitler** [comment]
LGTM

**Comment by khalidabuhakmeh** [comment]
It's going in boys and girls!

**Pull request merged**
